REPLACE INTO `roles` VALUES (1,'ADMIN');
REPLACE INTO `roles` VALUES (2,'USER');
REPLACE INTO `roles` VALUES (3,'USER');
REPLACE INTO `roles` VALUES (4,'USER');
REPLACE INTO `roles` VALUES (5,'USER');
REPLACE INTO `roles` VALUES (6,'USER');